name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Create dummy secrets.json
      run: |
        mkdir -p assets
        echo '{"api_key": "DUMMY_API_KEY_FOR_BUILD"}' > assets/secrets.json

    - name: Install dependencies
      run: flutter pub get

    - name: Build debug APK
      run: flutter build apk --debug --verbose

    - name: Find and Upload APK
      run: |
        find build/app/outputs -name "app-debug.apk" -exec cp {} app-debug.apk \;
      id: find_apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app-debug.apk